version: '3.8'

services:
  browser-use-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - IN_DOCKER=true
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      # DISPLAY é definido no Dockerfile, mas pode ser ajustado aqui se necessário
    volumes:
      - ./.env:/app/.env
    shm_size: '2gb' # Importante para Chromium
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
