version: '3.8'

services:
  browser-use-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    volumes:
      - ./.env:/app/.env
    shm_size: '2gb'
